#!/bin/bash

DEPLOYARR=("B:/bsouthga/child-insurance/ B:/childrens-health-coverage-at-risk/")

mkdir -p dist

echo uglifying...
uglifyjs -m --screw-ie8 app/bundle.js > dist/bundle.js
cssmin app/bundle.css > dist/bundle.css

echo copying data...
cp -r app/data dist/data
cp app/index.html dist/index.html
cp iframe_test.html dist/
cp -r app/images dist/images

echo creating tarball...
cd dist/
tar czfP ../tarball.tar.gz ./

echo copying tarball...
cd ../
rm -rf dist/

STARTDIR=$(pwd)

for DEPLOY in $DEPLOYARR; do
  cd $STARTDIR
  cp tarball.tar.gz "$DEPLOY"
  echo unzipping...
  cd "$DEPLOY"
  tar -xzf tarball.tar.gz
done;

rm tarball.tar.gz

