#!/bin/bash

DEPLOY="B:/bsouthga/child-insurance/"

mkdir -p dist

echo uglifying...
uglifyjs -m --screw-ie8 app/bundle.js > dist/bundle.js
cssmin app/bundle.css > dist/bundle.css

echo copying data...
cp -r app/data dist/data
cp app/index.html dist/index.html
cp iframe_test.html dist/
cp -r app/images dist/images

echo creating tarball...
cd dist/
tar czfP ../tarball.tar.gz ./

echo copying tarball...
cd ../
rm -rf dist/
mv tarball.tar.gz "$DEPLOY"

echo unzipping...
cd "$DEPLOY"
tar -xzf tarball.tar.gz
rm tarball.tar.gz
